apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-agents-carrier.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ai-agents-carrier.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
