"""The reads an agent needs before it acts: approvals, and spilled results.

Two gaps this closes, and both are about a caller that could act without being
able to look:

* ``approve_run`` / ``reject_run`` have always existed while nothing could
  *read* a pending case. An approval payload now carries ``change_kind``, a
  ``details`` map and a cell-level ``affected_sample`` — and for a generated
  write, ``details`` says a language model produced the values. Approving that
  blind is the failure these two tools remove.
* since results stopped travelling as values, a ref in run state carries
  counts and a three-item preview and nothing could read the rest. That is
  closed by putting data source results on the *same* rails as a data node's
  export rather than giving them a reader of their own — see
  ``tests/test_data_artifacts.py`` and ``tests/test_run_data_api.py``.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from unittest.mock import MagicMock

import pytest

from app.application import management_tools as core
from app.application.management_tools import ManagementDeps
from app.domain.models.approval_case import ApprovalCase, MetaLlmVerdict
from app.domain.models.graph_run import GraphRun
from app.infrastructure.persistence.approval_backend import InMemoryApprovalBackend


class _FakeRunRepository:
    def __init__(self, *runs: GraphRun) -> None:
        self._runs = {r.id: r for r in runs}

    async def get(self, run_id: str) -> GraphRun | None:
        return self._runs.get(run_id)


def _deps(*, approvals=None, runs=()) -> ManagementDeps:
    return ManagementDeps(
        registry=MagicMock(),
        run_repository=_FakeRunRepository(*runs),
        approval_backend=approvals,
    )


# ---------------------------------------------------------------------------
# Approval reads
# ---------------------------------------------------------------------------

def _case(case_id: str = "case_1", **overrides) -> ApprovalCase:
    data: dict = {
        "id": case_id,
        "status": "pending",
        "workflow_id": "csm-watcher",
        "workflow_name": "CSM Watcher",
        "run_id": "run_abc",
        "step_id": "write_status",
        "datasource_id": "google-sheets",
        "datasource_name": "Projects sheet",
        "operation": "set_status",
        "method": "POST",
        "change_kind": "write",
        "affected_rows": 2,
        "affected_sample": [
            "Projects!B2 (status): 'open' -> 'closed'",
            "Projects!B7 (status): 'open' -> 'closed'",
        ],
        "details": {
            "code_origin": "generated by a language model and activated",
            "range": "Projects!A1:Z500",
        },
        "targets": ["Projects!B2", "Projects!B7"],
        "params": {"ids": [2, 7], "status": "closed"},
    }
    data.update(overrides)
    return ApprovalCase.model_validate(data)


@pytest.fixture
async def approvals() -> InMemoryApprovalBackend:
    backend = InMemoryApprovalBackend()
    await backend.create(_case())
    return backend


async def test_the_pending_queue_names_the_blast_radius(approvals):
    out = await core.list_pending_approvals(_deps(approvals=approvals))

    assert "case_1" in out
    assert "write" in out
    assert "Projects sheet.set_status" in out
    assert "2 row(s)" in out
    assert "CSM Watcher" in out
    # The point of the list is to get the caller to read one properly.
    assert "get_approval" in out


async def test_the_pending_queue_shows_a_meta_llm_verdict(approvals):
    await approvals.create(_case(
        "case_2",
        meta_llm=MetaLlmVerdict(
            decision="approve", confidence=0.91, autonomous=True, model="m"
        ),
    ))
    out = await core.list_pending_approvals(_deps(approvals=approvals))
    assert "meta-LLM: approve" in out and "0.91" in out and "autonomous" in out


async def test_an_empty_queue_says_nothing_is_waiting(approvals):
    empty = InMemoryApprovalBackend()
    assert "No approvals are waiting" in await core.list_pending_approvals(
        _deps(approvals=empty)
    )


async def test_a_decided_case_is_not_in_the_pending_queue(approvals):
    await approvals.create(_case("case_done", status="approved"))
    out = await core.list_pending_approvals(_deps(approvals=approvals))
    assert "case_done" not in out


async def test_get_approval_shows_what_a_decision_needs(approvals):
    """Including that generated code produced the values."""
    out = await core.get_approval(_deps(approvals=approvals), "case_1")

    assert "Case: case_1" in out
    assert "Change kind: write" in out
    assert "Affected rows: 2" in out
    # The detail that changes how much the sample can be trusted.
    assert "code_origin: generated by a language model and activated" in out
    # The cell-level sample.
    assert "Projects!B2 (status): 'open' -> 'closed'" in out
    assert "Targets:" in out and "Projects!B7" in out
    assert "Params:" in out and "closed" in out
    assert "Run: run_abc step 'write_status'" in out


async def test_get_approval_surfaces_an_autonomous_verdict_and_its_veto_window(
    approvals,
):
    deadline = datetime.now(timezone.utc) + timedelta(minutes=10)
    await approvals.create(_case(
        "case_auto",
        meta_llm=MetaLlmVerdict(
            decision="approve", reason="matches ten prior approvals",
            confidence=0.95, autonomous=True, model="judge", history_size=10,
        ),
        veto_deadline=deadline,
    ))

    out = await core.get_approval(_deps(approvals=approvals), "case_auto")

    assert "AUTONOMOUS" in out
    assert "matches ten prior approvals" in out
    assert "Veto deadline" in out


async def test_get_approval_reports_an_unknown_case(approvals):
    out = await core.get_approval(_deps(approvals=approvals), "nope")
    assert "not found" in out


async def test_the_approval_reads_say_so_when_the_store_is_absent():
    """Silence would read as "nothing is waiting", which is a different claim."""
    assert "unavailable" in await core.list_pending_approvals(_deps())
    assert "unavailable" in await core.get_approval(_deps(), "case_1")


async def test_a_long_value_is_clipped_with_its_size_stated(approvals):
    await approvals.create(_case("case_big", params={"body": "x" * 5000}))
    out = await core.get_approval(_deps(approvals=approvals), "case_big")
    assert "chars total" in out
    assert len(out) < 3000


def test_reading_an_approval_costs_the_same_as_reading_anything_else():
    """The informed decision must not be the privileged one."""
    from app.infrastructure.auth.authorization import Permission

    assert core.list_pending_approvals.required_permission is Permission.READ
    assert core.get_approval.required_permission is Permission.READ
    # Deciding is still a write. run_control gates itself by raising
    # RunControlError(403) rather than by this decorator, so the classification
    # lives in the table asserted by tests/unit/test_tool_permission_gates.py.
    from tests.unit.test_tool_permission_gates import EXPECTED_TOOL_PERMISSIONS

    assert EXPECTED_TOOL_PERMISSIONS["approve_run"] is Permission.WRITE


# ---------------------------------------------------------------------------
# Both surfaces
# ---------------------------------------------------------------------------

async def test_every_new_read_tool_is_published_on_the_mcp_surface():
    from app.api.mcp.management_server import (
        build_management_mcp,
        register_management_tools,
    )

    mcp = build_management_mcp()
    register_management_tools(mcp, lambda: None)
    names = {t.name for t in await mcp.list_tools()}

    assert {
        "list_pending_approvals", "get_approval",
        "list_run_data", "get_run_data_artifact",
    } <= names
